---
title: 'Exercise 2. Data analysis'
author: 'Sasha D. Hafner'
date: "`r format(Sys.time(), '%d %B, %Y')`"
urlcolor: blue
---

# Overview
In this exercise you will analyze emission of methane from pig slurry samples incubated in a laboratory experiment.
Multiple bottles were used as reactors in a completely crossed factorial experiment with 2 temperatures and 2 headspace gases.
Measurement data were kindly provided by Frederik Dalby.

# 1. Read and check data
Read in the data in the file `slurry_emis.csv`.
Check the data.
The relevant columns are 

* `reactor`: bottle key
* `ch4`: methane concentration in bottle exhaust in ppmv
* `flow`: rate of gas flow through the bottle in L/min
* `day`: time of measurement from setup in d
* `gas`: headspace gas
* `temp`: incubation temperature

# 2. Data analysis
Use an appropriate approach to determine if the data show that incubation temperature and headspace gas affect methane emission.
Quantify any effect.

### My suggestion
I recommend using response feature analysis with calculated total emission as the response variable, fitting a linear model using `lm()` in R or `ols()` in Python.
But you could use other responses.
